### ISSUE TITLE
Initializing MSBuild project tools runs forever

### ISSUE THREAD

**Issue by TomSwiedler** [tintoy/msbuild-project-tools-vscode#143] opened 2024-02-14 14:59 UTC
When starting VSCode the Initializing MSBuil project tools runs forever trying to download DOTNET CORE 8.0.

DOTNET CORE 8.0.2 is already installed.

DOTNET --info:
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e2473a36

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\dev\dotnet\sdk\8.0.200\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.407 [C:\dev\dotnet\sdk]
  7.0.404 [C:\dev\dotnet\sdk]
  8.0.100 [C:\dev\dotnet\sdk]
  8.0.200 [C:\dev\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [C:\dev\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\dev\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\dev\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\dev\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\dev\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\dev\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\dev\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\dev\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\dev\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\dev\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\dev\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\dev\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\dev\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\dev\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [C:\dev\dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by tintoy** [comment] 2024-02-14 20:07
Hi - are you able to post the log from the output window where it talks about trying to download .net 8?

**Comment by TomSwiedler** [comment] 2024-02-14 20:12
tintoy.msbuild-project-tools requested to download the .NET Runtime.
Downloading .NET version(s) 8.0.2~x64 ........................................................................................

The dots go on forever

**Comment by tintoy** [comment] 2024-02-14 20:58
Hmm - that’s odd; I’ll see if I can figure out how to get the .net acquisition extension to log more extensively…

**Comment by tintoy** [comment] 2024-02-17 00:40
Sorry for the delay, work’s been a little full-on this week.

are you able to try the steps linked below to point it at your existing dotnet installation? I’d like to see if the problem is with detection or download…

https://github.com/dotnet/vscode-dotnet-runtime/blob/main/vscode-dotnet-runtime-extension/README.md#i-already-have-a-net-runtime-or-sdk-installed-and-i-want-to-use-it

This extension has the Id `tintoy.msbuild-project-tools`.

**Comment by TomSwiedler** [comment] 2024-02-17 18:32
tintoy.msbuild-project-tools requested to download the .NET Runtime.
Using configured .NET path: C:\dev\dotnet\dotnet.exe

**Comment by tintoy** [comment] 2024-02-17 22:21
And does it still do the dots forever?

**Comment by tintoy** [comment] 2024-02-18 02:56
I wouldn’t have thought so; I’m still trying to reproduce the issue but I’ll try setting up a container tomorrow morning and see if I can get it to happen…

**Comment by TomSwiedler** [comment] 2024-02-18 11:31
It did not attempt to download again for me

**Comment by tintoy** [comment] 2024-04-30 03:24
I’m going to have another try tonight at reproducing this locally (sorry for the delay; I’ve been away on vacation) 🙂

**Comment by tintoy** [comment] 2024-05-04 03:12
Hi - I've spent a couple of days trying to reproduce this behaviour but have been unable to (at least with the currently-released version of the extension).

Is anyone still experiencing the problem described in this issue?

**Comment by TomSwiedler** [comment] 2024-05-04 11:41
I removed the configuration for the extension from the settings.json file and it appears to still be loading properly.

**Comment by tintoy** [comment] 2024-05-04 12:23
Great! Thanks for checking 🙂

I’m going to close this issue for now, but feel free to reopen it if the problem reoccurs.

**Closed by tintoy** 2024-05-04 12:23 UTC
Labels: area/host, investigating
