### ISSUE TITLE
Autocomplete/Intellisense Only Works After The Last Grouped Entry When Initiated By `<`.

### ISSUE THREAD

**Issue by vindicatorr** [tintoy/msbuild-project-tools-vscode#129] opened 2023-09-20 01:42 UTC
Take the simple skeleton template:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

Success (intellisense):

- Press `<` between `  </PropertyGroup>` and `</Project>`
- Press `<` between `    <Nullable>enable</Nullable>` and `  </PropertyGroup>`

Fail (no intellisense):
- Press `<` between `<Project Sdk="Microsoft.NET.Sdk">` and `  <PropertyGroup>`
- Press `<` between `    <ImplicitUsings>enable</ImplicitUsings>` and anything surrounding it.

Other findings:

- Wipe `k>net8.0</TargetFramework>`, press CTRL+SPACE, and receive `No suggestions`.
- Add `<TargetFramewor` (where cursor sits after `r`) after `Nullable` tag. Press CTRL+SPACE, and get the ENTIRE list of options. Move the cursor left, and the list is filtered. (this point and the one above both seem to be related to the position of the cursor)
- Add `k>` after `<TargetFramewor`, and the autocomplete doesn't fill out the rest as it would have with a tag selected from the list of options. One would hope after the `>`, the remainder would be filled out. Look-behind for the entire opening tag, then look-ahead for a closing tag that would be associated with it. If it does not exist, fill out that remainder.

**Comment by DoctorKrolic** [comment] 2023-09-22 15:14
Duplicate of https://github.com/tintoy/msbuild-project-tools-server/issues/71. Nevertheless, thanks for reporting!

**Closed by DoctorKrolic** 2023-09-22 15:14 UTC
Labels: area/xml, area/intellisense, investigating
